#!/usr/bin/env bash
# Redirection
sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start

redirection_url="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Check if the location block already exists in the Nginx configuration
if ! grep -q "location /redirect_me" /etc/nginx/sites-available/default; then
	# Use sed to insert the location block into the default Nginx configuration
	sudo sed -i "/location \/ {/a \    location \/redirect_me {\n        return 301 $redirection_url;\n    }\n" /etc/nginx/sites-available/default
fi
sudo service nginx restart
