#!/usr/bin/env bash
# Redirection
sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start

sudo sh -c 'echo "server {
	listen 80;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html index.htm;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > /etc/nginx/sites-available/default'

sudo service nginx restart
