#!/usr/bin/env bash
# Redirection
sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start
directory = "/etc/nginx/html"
file = "/etc/nginx/html/404.html"

if [ ! -d "$directory" ]; then
    sudo mkdir -p "$directory"
fi
if [ ! -e "$file" ]; then
    sudo touch "$file"
fi

sudo sh -c 'echo "Ceci n'\''est pas une page" > /etc/nginx/html/404.html'
sudo sh -c 'echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default'

sudo service nginx restart
