#!/usr/bin/env bash
# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.9
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy=2.9.*
sudo sed -i -e '$aENABLED=1' /etc/default/haproxy
sudo tee -a /etc/haproxy/haproxy.cfg <<EOF
frontend http-in
	bind :80
	default_backend webservers

backend webservers
	balance roundrobin
	server 239778-web-01 239778-web-01:80 check
	server 239778-web-02 239778-web-02:80 check
EOF

sudo service haproxy restart
