#!/usr/bin/env bash
# Add HAProxy PPA
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo tee -a /etc/haproxy/haproxy.cfg <<EOF
frontend http-in
	mode http
	bind :80
	default_backend webservers

backend webservers
	mode http
	balance roundrobin
	server web-01 54.85.132.25:80 check
	server web-02 34.201.165.191:80 check
EOF

sudo service haproxy restart
