#!/usr/bin/env bash
# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.9
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy=2.9.*
sudo sed -i -e '$aENABLED=1' /etc/default/haproxy
sudo tee -a /etc/haproxy/haproxy.cfg <<EOF
frontend http-in
	bind :80
	default_backend webservers

backend webservers
	balance roundrobin
	server web-01 54.85.132.25:80 check
	server web-02 34.201.165.191:80 check
EOF

sudo service haproxy restart
