#!/usr/bin/env bash
# Installs Nginx on server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

sudo sh -c 'echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
}" > /etc/nginx/sites-available/default'

sudo service nginx restart

