#!/usr/bin/env bash
# loops from 1 to 10 and:
#	bad luck for the 4th loop iteration
#	good luck for the 8th loop iteration
# 	Best School for the other iterations

i=1
while [[ $i -le 10 ]]
do
	if [ $i == 4 ]
	then
		echo "bad luck"
	elif [ $i == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i += 1 ))
done
