#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes

hr=0
while [[ $hr -le 11 ]]
do
	min=1
	echo "Hour: $hr"
	while [[ $min -le 59 ]]
	do
		echo "$min"
		(( min += 1 ))
	done
	(( hr += 1 ))
done
echo "Hour: $hr"
