#!/usr/bin/env bash
# a Bash script that displays:
# The content of the current directory

for file in *;do
	if [[ $file == *-* ]]; then
		name_part=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name_part"
	else
		echo "$file"
	fi
done
