#!/usr/bin/env bash
# displays all active IPv4 IPs on the machine it’s executed on

network_info=$(ifconfig)
ipv4_addresses=$(echo "$network_info" | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{print $2}')

for ip in $ipv4_addresses
do
  echo "$ip"
done

